### ISSUE TITLE
奇怪的˜ Ddenoised

### ISSUE THREAD

**Issue by Goldbeanbean** [luxinyayaya/PerpCorrect#1]
请问算法1中提及的算法2的输出˜ Ddenoised怎么得来的？算法2显示你一开始赋了个 ˜D,就没有处理了，什么鬼？DDonised又是啥？

**Comment by luxinyayaya** [comment]
感谢您的关注，非常抱歉，DDonised 是拼写错误，实际应该是 Ddonoised，算法2得到的输出是在19行和31行。

**Comment by Goldbeanbean** [comment]
感谢回答
